language: android

android:
  components:
    - build-tools-21.1.2
    - android-21
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - chmod ugo+x .buildscript/deploy_snapshot.sh
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "TNFd1b7lROc37OyM+jO/aEKXgaM08evL+zDYt9xCVCVmbTbfcw41FVijwMEVpCvV2NQGCfZaFudePGUeFxjIevlXeKlspSmoUGV3uP1CS52qWYHw0QH8R45Wbwm2ZM6lqO/qfl0RNYLR7lnGSZ4N6gySzTqjb+jBFhbokqQyyD1mQ0wD80fa/zFx8OdQRrgAlgUAYYzsRx4NfMEksHQaqes9rMkhDPuSG9N9qA2UUE1az1uvoWx438k+UlvRifkKV4g9hSfaEKfEJxqQ/YZWwnmEDX4WNTS8GNqQrxItSDjhpQrjbEuH6+F/3euxz5KJj/KRVcHfxFpvUhhDkEIP+CmHuq99MMYkpNJYozfIyWNGEAWaOTjZ1SZiL+nWXSNYVgUQ0sFe3LFNkZ7OfN0VFBCAuP2m26ugbmCGJjaY6ohUqmj6HQQ+1f0ZoRkcOljo4gdX4tf762V1QTGzsCY24EtczULCPyfRoHHgcz9HwvhHVe1BRhLcVcAdWZsquBAK5nARYcU2lEzWNZGkDgAapmK+hF2F7AnTnA7UfWL6+RtIDD/nRqwUkQyTNLrnKaZLZVJIfQLbCLIxSCcuZagKBtSPcueVhwldkGdWmxvrPXhzJguHPcxUShYlhhUv/KrLthvbJpRuEvBz3cMtW88lnp/5bJOm4Z22fV+57Yrs1Rk="
    - secure: "yA9ZQ6MtF93gWaNcJtdZapZ4op30FBTuCC1nOs1BgnYn4sGK8mmjk+cyTykj8T1DdiLO4IiFPr7JeQtt030TdpKp9LdjAOs1+mFUWVK3HfvZ0BjOnIXmZfdUKJjpmXjAMgvFLk4uAzUC29ZsHxJuYjo98VZmmcDVRTaLDGq1MvCkUrhEjmTvUwRy8zbcj9ZFOCSecwMrPW/3Zy6UWqBxrrRlzxaFm3DNPds9bEAHpNFupruo9Ry4jnrqtVg24OLEVcwWbtwaxkeVK8ghl7iXEyWeONuXE0sZrSjr5nm4uRvRoQ3P4dJ2leQTPlGqwMuggFI9FahRoWVAMkDxZ01tsCqEz2yGkvDs41ODfFLtIjGEGuNlm79FeQ+5ZW9VXzneKmFwotk4u5S296jO22a9myeHegk1KH3Z+O794ZmDP6xamr3H+yPs5hSiEaic1+mJVZj2eZ9Vf/y7LwFUe+Ln1P1HyNOF0hnE7z/dbFYH0/dTv/UJDV3RdfrTQ6prsRPyoluqAy7sW9sWp9kB9S53SU/qDyxvS/M3/dkqlKMmUryjS2JWGUH5CwMcEhJ34I29vpSEjv42Fe+9cF9Cl7oqtvRFdYfpdjlg2aZ/j9osB0qJuVZ0+fqspIS3Ybh4bYPFqXLeoe2LElTILBaWrvZ0ITrrhBmUm4gWAaycZtdT0+Y="

branches:
  except:
    - gh-pages

branches:
  only:
    - master

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
